<?xml version="1.0" encoding="UTF-8"?>
<testrun name="ContraceptiveTimerTest (1) (Failed Tests first)" project="ContraceptiveTimerTest" tests="8" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" incomplete="true">
    <testcase name="testGetIntervalDays_TypeIsPatch_Returns7" classname="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" time="0.401"/>
    <testcase name="testGetIntervalDays_TypeIsPill_Returns1" classname="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" time="0.078"/>
    <testcase name="testGetIntervalDays_TypeIsRing_Returns21" classname="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" time="0.182"/>
    <testcase name="testNumberOfDaysSinceLastBreak_StartTimeAndLastBreakIsYesterday_Expected1" classname="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" time="46.873">
      <error>Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
</error>
    </testcase>
    <testcase name="testAndroidTestCaseSetupProperly" classname="ch.kusar.contraceptivetimer.test.businessobjects.AlarmDataTest" incomplete="true"/>
  </testsuite>
  <testsuite name="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" incomplete="true">
    <testcase name="testLoadFromStorage_LoadsStoredFileIntoObject_ShouldLoadTheSavedDataCorrectly" classname="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" incomplete="true"/>
    <testcase name="testSaveToStorage_StoresTheFileToInternalStorage_ShouldBeSavedToStorageWithoutError" classname="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" incomplete="true"/>
    <testcase name="testAndroidTestCaseSetupProperly" classname="ch.kusar.contraceptivetimer.test.wrapper.InternalStorageWrapperTest" incomplete="true"/>
  </testsuite>
</testrun>
